package spokay;

public class PuzzleInputs {
    public static String day1Input = "xt36five77\n" +
            "two8five6zfrtjj\n" +
            "eightthree8fiveqjgsdzgnnineeight\n" +
            "7chmvlhnpfive\n" +
            "1tcrgthmeight5mssseight\n" +
            "eightoneqxspfzjk4zpfour\n" +
            "fdbtmkhdfzrck9kxckbnft\n" +
            "9six9\n" +
            "goneightczdzjk18589\n" +
            "41two3eightfscdmqjhdhtvsixld\n" +
            "t8929\n" +
            "fourtwoxsxqqmqf3sixfoursixmmjhdlx\n" +
            "bcbsfd14cjg\n" +
            "95three6threendpqpjmbpcblone\n" +
            "tdmvthreeonefive8574\n" +
            "5eight82sixtwonev\n" +
            "ninemg2shhmsqh\n" +
            "thmlz4\n" +
            "xtxjmm2tbbntrmdqxpkdjgh1vzjvtvg7nine\n" +
            "vf19fourddfsvmzeight9\n" +
            "mmg6fivegcthdonesix1eight\n" +
            "7rzzdknxtbxdchsdfrkfivenjtbrjj\n" +
            "2sdzxhxp\n" +
            "vzvkjvngfjsxmponep9jppnqnbt8jtwo\n" +
            "85fourfivetwo6xvhfxone9\n" +
            "fivecgtwotwo3oneighth\n" +
            "pbmninesixzcqs5\n" +
            "ztlhxfmr4mcjnd3two\n" +
            "nfr27zdxchz\n" +
            "sgljlqlcxsnjgppxgqxppqszzgbp7\n" +
            "five78eightthree\n" +
            "mleightwo68\n" +
            "threemnnbjncqq68fourmjdfqzqxbdqvfftggf\n" +
            "twofive35llpqrhptnv\n" +
            "pslmgrznfzt823sevennx55\n" +
            "72fivesevenvnxpkoneightgdm\n" +
            "1sixfdjtgxbflfkvv\n" +
            "77three9\n" +
            "five6skbsrr\n" +
            "fjvlsthreeffzbjlsm2\n" +
            "6dpkrlbxfdv5nine1499\n" +
            "jvt9one28nine29\n" +
            "57pbgvccprdgnine49three\n" +
            "qmthreekcsttzmgd1nineone7dvhsjg\n" +
            "eightqpfhvqnpbbrbmsz76\n" +
            "vvqjsevenfourhmdn45\n" +
            "2eightxgkdtdkfbtcjgrlthreefivekm2\n" +
            "rfpklsh1threenine\n" +
            "nrhbjqpxssmqbkdbzg2\n" +
            "556ghndxkrg9\n" +
            "3six8\n" +
            "zhkkgqllq9eightninebspgktnh1krfbzdcthreekzxzgszgpd\n" +
            "933five\n" +
            "sixsix5qmbqd\n" +
            "7sevenxckssckcrqnpmfiverqtcdclnkzpztt\n" +
            "5eightpdsvjknine813tnz\n" +
            "k81one\n" +
            "6threegsx48\n" +
            "three3xbqvcfgjjfsixfiveone779\n" +
            "threenjtlxnonexqhv1\n" +
            "5ninefourtwofsqdbchtpkfiveninencsdrnvnbf\n" +
            "vdveightsixthree1\n" +
            "2mrxnnqngfmshdz\n" +
            "qfourmjpltwolblkzlkdfr41vmskjgrqkv\n" +
            "8hbjcnseighttwoseven\n" +
            "28lvggdhbjgqth\n" +
            "nineshpzfshzm68ttlqbqxxrvdxrkvdkbcnfdkrhcqpqrfmpxtwo\n" +
            "9hhfninefourfiveczdbrn1\n" +
            "2dpzvd39eightwohjc\n" +
            "3zrhnzvq79fourxgldtbthree5\n" +
            "two1716\n" +
            "bgkfjkeightsevenf9gclhlprxlk3\n" +
            "nbf2rdglrfourthree86xfpqckg\n" +
            "hslr84mkdcqpl3qtszqfngthreeonenine\n" +
            "7bhgqcphnb2fpjrbvrlstvghqbkfive1\n" +
            "6lkfdcddkbsevenxsixseven2fsg2eightwos\n" +
            "3xjprzkdsckltdone\n" +
            "1qbkshbrcddjtjz4jhrdmpnrq3mmfive\n" +
            "27five3sevenfourjhhv\n" +
            "5fivevhkttflkone4\n" +
            "5jcthxvhglfourkjrhfour\n" +
            "3lbgzfkljfzkf3\n" +
            "9tmpczsvskqqtveight1\n" +
            "kfrjhgsixfive9three1\n" +
            "onesixpdf8onethree1\n" +
            "onesixnine5\n" +
            "1lscknhb\n" +
            "fourhrnmcfgpzffhdtbdcpdbxqh3\n" +
            "twoffcbgcjnsix667\n" +
            "sevenfc14\n" +
            "8kzzrbz2threecclhhjn1l\n" +
            "kqqpzbbqkchmkdl46twothree453\n" +
            "8two3jqxmnz\n" +
            "eightpszqltlncjpfrdfzffltnthree4\n" +
            "eight8eightsixdcgqnbvt1lbhlchdzkf8j\n" +
            "64nine\n" +
            "3twofivetwosevenfour9\n" +
            "lhlntlsixtwojqhsevenone74\n" +
            "2242eight865p\n" +
            "dnhfbgzcvsx5krv26\n" +
            "szdnjvh9\n" +
            "hrzczjbfphxvjqs8one19five2six\n" +
            "lvvkjjvgcjbkhbdnf6ninesqgqhthseventbkzhjbnrb\n" +
            "crmcpjhfmgeighteight316\n" +
            "vmfqlrnjjnv7fourkqbsfsnnqxfqsixthreesix\n" +
            "7sevensj9919one\n" +
            "hrvtbr2lqkkhn25three318\n" +
            "rngggthlrfoursix2twopv\n" +
            "3srcpjlqt43eighthscbffksixfoursix\n" +
            "885sixbftpfive\n" +
            "qpfkxbqfph9sevenc2\n" +
            "9zrtbhztseven\n" +
            "5bcgdvdtzjjbseven41nineeight\n" +
            "two3szknm\n" +
            "klfivethreenine2qdpbp4eightwoqf\n" +
            "1b\n" +
            "8llkrslcbcsfivecqclmfrxbkzfive\n" +
            "twoseven1\n" +
            "six3ninefivehtxjqjgv6onepkfgjcczft5\n" +
            "oneskjsh5jmnhsxhfoureightfourcml\n" +
            "thjptkn9rpjkbkvgm2\n" +
            "glpbbfjgfivep1696xhcprcqxone\n" +
            "5fivegnsbzt8gtxvhfmt46\n" +
            "fivefoursevenjkxqlcx7onenine\n" +
            "lfourghzdksztjmfour4threepdnfsz6\n" +
            "two7one\n" +
            "1onesixdzh\n" +
            "7ftphkqlonesxsrlgkczjthreefive3nine\n" +
            "62ninefivefkbmhvlltfourtwo2one\n" +
            "rgoneighttwortjczm24seven\n" +
            "chqxcv3fdqnjngqkkkrvlcgtdfdsvztx\n" +
            "three2dvfpsgjfgs16fmvninefourfrvg\n" +
            "five4bgbfrj52\n" +
            "98sixsevenfourzdsfjddbmbrffkt1two\n" +
            "nine9xhkcmmvb81onehsmxclb\n" +
            "6146four\n" +
            "slmhsix4hhtrdfdjpk2fiveonec\n" +
            "1oneightd\n" +
            "86sevendgdbnrvgjnmtxrmqtt\n" +
            "six56three2hslccxbnzpmbrctd4\n" +
            "seven8nine3fiveddvpdjgqrjtwovhbdmtz\n" +
            "five32\n" +
            "769three1\n" +
            "mdcmrbj19\n" +
            "threethreevc6bknnspdvbfzsevenghqnkxnhfxjf\n" +
            "sevensevenzvqkvvgzn12two9bfzfpxjhfslqs\n" +
            "8mmqrvzklbfivenineeightwohnp\n" +
            "zngczscnv8threesevenfourtwo\n" +
            "695eight8szhqcklnc1\n" +
            "sevenjvnfbbnnine9ninefour64two\n" +
            "four5threelqtwoxhvhjnkgz2\n" +
            "ztnzbgmtdtwonineeight3\n" +
            "twosxfour6xsshbnhsixsix1\n" +
            "threesevendmfivesevendxhsdhsevenqnrvfrgpfl5\n" +
            "71dbpsk4\n" +
            "eightxqzh1clmrdljnxh\n" +
            "jqjthreetwo3\n" +
            "23sixhsvmstwofive\n" +
            "mhvttrxpllkfpxzcfvjtpkfsgd21jtrcrgp\n" +
            "1lcqlznsbdzksklm38frfhdpt\n" +
            "8vjtzvxvfive\n" +
            "9xbcgqhdclrzdnzspllpfrqhnxztftninethree1\n" +
            "seven5two\n" +
            "fourj5ldxlnine\n" +
            "sixtwosix73jjtrvt\n" +
            "9qqbmccrg8xdgcqmnine84\n" +
            "fivedmsdlsfour2rmjxqthxfcsgkqgsxxqbtwonesj\n" +
            "one631p\n" +
            "6x2\n" +
            "93nptkkseightkkgnsnqkpfourone\n" +
            "173\n" +
            "eighteightvzvxr2pqknnccxqkznc\n" +
            "ftbsixnine4\n" +
            "fiverpz9ldmbrqhg\n" +
            "7pzbjtnqcfour4319eightcxpgl\n" +
            "tchdxgqsqeight8ftllckrz1\n" +
            "kz2five\n" +
            "scgflstwo6zzdxdcs\n" +
            "535svzdxtwo4\n" +
            "7fourone2\n" +
            "kqczhqqttf74seven\n" +
            "ninesixnttqqzmdg264\n" +
            "sevenfourthree2one9\n" +
            "eight1rnnsppqbjzv7jknltmlb2\n" +
            "6eighteight5cljzvzdtqq8sqftf\n" +
            "ninebnpxdqs1\n" +
            "seven2nineeight\n" +
            "hjnnqsnfftjstkrlknvlqlkfsdbgz8\n" +
            "rcbhxcfmkc3ptnt2\n" +
            "threesix378twostfsjjvmnseven\n" +
            "hllssqjbc41\n" +
            "six9zbkrrvmxngjone5xqjbxcrkhzr\n" +
            "nineone57\n" +
            "3pls\n" +
            "sfcdbhkdrpkdrtxtvlkqfiveqvbxhvm8\n" +
            "fourthreemeight7nine9\n" +
            "five5fivesfnxfour\n" +
            "h3two2sixgkninetwo1\n" +
            "53ccblnvbqhjxgbxrs1tk\n" +
            "twotwofxvcmsld2zbjlqzvgzkqvnthfvsftwo1\n" +
            "eightninevdxxdglskbfzz8sevenfour8\n" +
            "flhjjt6seveneightlqpfvnpxvthreesix\n" +
            "threefiveonegpcjjvv6fourseven\n" +
            "9pbxlqdkprzcxp\n" +
            "cblkxjmpgrfk5\n" +
            "qbntftctnine5five3bsevenbskhvtm\n" +
            "7eightsix3threehzn\n" +
            "5nhndlxkthreeseventwocdvnhzrcszhd\n" +
            "six5onekbctwo\n" +
            "fivezhtlpveightvdfltnxpvrzmczdzb9q\n" +
            "nine9xsfq8vtdpmcfgm2\n" +
            "onesl8mqzgdrstwofour\n" +
            "4onedqtrcc58ghlgxqjlbv\n" +
            "132zvtptdrqt\n" +
            "ftwone1tkzzthvdsevenseventtgvqnbzf\n" +
            "prxrsfvdbt73zblz6four84seven\n" +
            "onefive1xllptjtwothreehsdlgrmjssfgk\n" +
            "twofiveeight781mgjxgzlmgkv\n" +
            "483fbgsx5\n" +
            "four82onefour\n" +
            "229683five\n" +
            "2onevncxhvscnbtngbzlbbpdnnntr\n" +
            "275cpjnine\n" +
            "j4threefour7dzqleight\n" +
            "ddgmsvmfz7brjdxt5\n" +
            "sevenfzjtxjtbmj8fivefive6\n" +
            "tqprcctwofive8sixzmgvphmdsmjtwocbpqc\n" +
            "sevenseven4fourbcscfcprcr5647\n" +
            "tghsix8\n" +
            "two83six9sfp99\n" +
            "fourthreefive3seventwo\n" +
            "7threepx\n" +
            "oneeight69sixgdzbbmlsh\n" +
            "23onelrdvbzljtcdjqckntwo7\n" +
            "six8onefivepgs\n" +
            "83gnxnjgvdr2four5nine6\n" +
            "lgfcvptthreesixthreeeightthree23\n" +
            "seven8gsqznnpb3\n" +
            "dqr478fivezxtwo\n" +
            "4cgkjbl261\n" +
            "pnjeight84twodnhh4\n" +
            "zeightwozhxshspt45\n" +
            "8rzkpmzlvszvdvonesixeight\n" +
            "twotwothreeseven95threethree\n" +
            "sixbr293sixthreesixnine\n" +
            "3sixsixthree9\n" +
            "q17ninenineseven8\n" +
            "jmhbhqjxvc72qsrhzzpnljeight775\n" +
            "456jnrtpfseven\n" +
            "gjcbnbdkt94dsjrgdq1\n" +
            "five56g6\n" +
            "rvjq8dkngcfjdd\n" +
            "twofive43\n" +
            "sixzz9threektkqmfq4gkxxzbg\n" +
            "2four7four\n" +
            "four3eightsvmnfive6\n" +
            "ninelvxcxdrxk1mvhtptlpqvff\n" +
            "qrbtlxbkdrjzkznqp6\n" +
            "z2xdrtqzzrbt9five3five5\n" +
            "twoeightsevenfive83\n" +
            "73lzgb1\n" +
            "oneseventwotwothreemr4dfkjlgshjzvlxqqoneightvvr\n" +
            "5twonvhrbtgfxdlvxrgnpkeightzjpd1\n" +
            "twotwo6rdfc\n" +
            "six84sevenfschptts1fg7\n" +
            "8kzqv\n" +
            "hnbjfivettpzkb8six\n" +
            "nine8zcrzgqntworxnj2three5\n" +
            "1qbjtsqqrttwones\n" +
            "gnjmvqrhnsfive5prbzfsjteightqgfcx2one\n" +
            "fivefour8btcrpntwo6oneeight\n" +
            "kfxbxn4283kcjpkbskshjdss9\n" +
            "3threethreeh\n" +
            "bmzjktnnrl8fcmmbtgzkj\n" +
            "vhnine84seventwonine\n" +
            "gq639rhqlbzp21qbseven\n" +
            "6rnineptdmntjsix6cnhhbcn\n" +
            "sixscrdone3mhgnmflzxftwonvkxvrftqcxzcfhdgxlvreightwos\n" +
            "6nine6gngneightlvqmmjjtdkrklqbthffhtwothree\n" +
            "bsn4rrgvrjdddhdfsvsffbqnrsbvtfive\n" +
            "twozflqcsix53jcsc5twohdeightwofb\n" +
            "73rx\n" +
            "xldqxlmfcdrnthree47tz6\n" +
            "foursix6ksrzponeonepdbfpjzspp88\n" +
            "czvdzccj9nine7\n" +
            "92one\n" +
            "9one8three\n" +
            "onevfzkmmcrtwotwo2five\n" +
            "8eighttwo6xpfxtvvpx\n" +
            "83four9\n" +
            "3fourdmtqtvqthree2ztvvdjzmfc\n" +
            "8fourpb7jjlcbkxkxfthree44\n" +
            "9cchfourltlxpbjpdrdplrqgrqpk1\n" +
            "fiveeightxlxmr5\n" +
            "bgrczrdsfrcfrpkprdncbkd55qnhjnzkbpninekbmgnlqgmxfqgndc\n" +
            "6jhcjhb57sfive8oner\n" +
            "six6twofive3ckthree3\n" +
            "xfxkfourtwokqcpvhzjjzsrxjm6\n" +
            "four85\n" +
            "p3foureight3rl\n" +
            "f6four2eight295\n" +
            "1onevonelslgmbq\n" +
            "pzj6pmjone94\n" +
            "bkmcjnllrmcfpmqckl3fivenljfgeightvrjfb\n" +
            "kgsczqtwo8qnjhtpfltonepvfive\n" +
            "fourfive5pfnlnjqd\n" +
            "vgrsfxtkcxfstsevennine89\n" +
            "njkblck4phphvmq7\n" +
            "ghflplsgkljsfk5\n" +
            "rtbm32lntjflptp435twosmtb\n" +
            "45four\n" +
            "fiveone41pqgcjt\n" +
            "threesdnllrxbxmhtcmjvdktqqkzs1\n" +
            "5one14zmxblkh3\n" +
            "4mzzqpmsfour5pnzonerdseven\n" +
            "9bhcxsnxdv7\n" +
            "twoxxjnsxxjxfnrtnknseven29c\n" +
            "four54gkcrncmjtpvfbdqr\n" +
            "mmvgl8onekzq\n" +
            "tprfvqnine54rqjkchkxtcrk6gxjgbfqpxg1\n" +
            "threeghtxbhkkrvxxcrvslhnvczxnine5four4\n" +
            "bkrkeight4jvjvmnine\n" +
            "sevensevenmphmhvhtjxcdcrcgbdvlmcr6mczlh\n" +
            "eight74seveneight5eight4one\n" +
            "bspq9fiveklkbeighttwo\n" +
            "51four\n" +
            "sevent79zngvzhhlxjrnrbkvnine\n" +
            "six3threepsjhtfoureight9\n" +
            "44mvfhcthpbv\n" +
            "3fourmrdzqlvb63hrzhqxc\n" +
            "7fivesixcnxfourpfour\n" +
            "csix4\n" +
            "qqtjk43\n" +
            "eightnhqpxttth9ddbfjpqjmfour83three\n" +
            "slx6fdm9bspmbxdqjfmkhr\n" +
            "stlxrvseven1gnmnqrnlthreenine\n" +
            "56zjfdrb\n" +
            "sbcxqp8\n" +
            "7eightsix9eightseventwo\n" +
            "7twosixfour\n" +
            "1eight6\n" +
            "twor59eightfourkpsix\n" +
            "571fivefdpntmjqgnineftpjtkh5\n" +
            "two7nsdz\n" +
            "pmf5twoseven4prgqz\n" +
            "7vfmvlgtvkbxnq\n" +
            "eightstdrhhtctthree61fourbmcvhmxtkdhcltxpr7\n" +
            "fdjcssixninetdgtbkgj4snzpqlninehvvkthree\n" +
            "122pqtcthreesixeight8\n" +
            "hfztkh2ksjnj43nine\n" +
            "sdlnm59onekdbdrdksixktk37\n" +
            "4mf114\n" +
            "8foursixninetwoxbcnq\n" +
            "vbhspqrkvcvpfour68xncb3kdbr\n" +
            "eight841\n" +
            "2fdr7fivehtnvbk7nine34\n" +
            "eightsixone1qzp4nxzrslmzrsix\n" +
            "two3zdjntkkcmdpheightfive\n" +
            "44one\n" +
            "17txlqkttvtzhzkjeightcqtpqzxlktxm\n" +
            "two8xcvpzppmzntzr\n" +
            "pbqeightwoncjsvrlzrkspcnqsrrfivefour5\n" +
            "9foursix1onevflhjngtthree\n" +
            "gp3qjmnsksn3nineeight4\n" +
            "39fdsdqonefleightwopsp\n" +
            "2dfzsfssnpbzfour\n" +
            "stzzclzgskgbztvrfqgbrms6\n" +
            "5zpq81threegdg\n" +
            "6three9ninethreeeightsevenninehhgqhxfhlv\n" +
            "1tqftcgtwo\n" +
            "zpkrjxfpzf5jmpqvxrgp6threexbjlzclxpneightscbrsgnine\n" +
            "two4bmlztrzn1\n" +
            "seven9klmsfmjtjr7sph\n" +
            "sixsix4\n" +
            "stldx46three15four98\n" +
            "gthb7nine\n" +
            "lninethreebrzzntwo4\n" +
            "6fvhgpqj5sevencgmm\n" +
            "75two7qktbnpcxtk\n" +
            "fbkzzsixgshhmzdgt9\n" +
            "xfivenineseven1dtzsfive78\n" +
            "four3ptvfmkkhzjsix\n" +
            "j9txxgmsvxx\n" +
            "seven9lmxhzthbnbbxjmbqkpsntbfourone\n" +
            "712fourlqknine4\n" +
            "xlpnrk64qnjjvszbtkgktbn\n" +
            "lznpdmrcxmzhsjqkc2cjm3zcx\n" +
            "615sevensix\n" +
            "phgjnmqfsqgjtqvzhpc3234qpkpjmxbfr\n" +
            "tnrtmcdljzq1three62\n" +
            "bcndkzgzp5sixhflsix3lgc\n" +
            "dqgmbkxlv4onetwo\n" +
            "freightwomsix916zrcsjgkktprb91\n" +
            "fourbcmprdvkbl9vxzfkcjfsqdlbndmrsq\n" +
            "sevenninezpblthreesix2threeqrcdpjqjgm5\n" +
            "5jnnine\n" +
            "j9fivesix1zhplxlvxsninefour\n" +
            "dm68htnmqdsnzjvqrrj\n" +
            "8four9pfvjjhrbzmlvhvtseven\n" +
            "two256six6qdpldblvleight\n" +
            "ninecprgdrmc2eight91mggqdvhcf\n" +
            "sqbccsh81t\n" +
            "1twovfhbngpggbgff8eight\n" +
            "bxdstkqnbhkvt2three2fg29\n" +
            "one7threehxcttwosixfourpx\n" +
            "brnine1nineone\n" +
            "6fffrqfjprmdx6sixseven\n" +
            "7four4fourx8sixfour\n" +
            "951seveneightnine\n" +
            "fivefoursix5tg6dpdxrckdh\n" +
            "829schqjxjdxncs6\n" +
            "seven1twockldvjsbeight\n" +
            "csjv58dshcsdrkgsixrdl\n" +
            "nineeightstjnxcgzbxrldsevenfour857\n" +
            "oneqpndxmthreemnmlnqnffv7\n" +
            "twotwo8qkdfcxvd253bhd\n" +
            "sevenfour3\n" +
            "t2sevenfgmjjrg63fourrvlz\n" +
            "4six9fivelbkzffrvsoneightxsj\n" +
            "nkkdsbp7kkjchhfckqqxfourthree9\n" +
            "7eightone4fiveninevxtrmbhfbrone\n" +
            "onemjzfsvsbh2vmsxdmcncjlnvtsqszv\n" +
            "eight26\n" +
            "sixseven7four\n" +
            "cpkzctmhpmpgtwoqfeight79\n" +
            "vplxpx9tndmcpsone2\n" +
            "eightone2bqlmdmf\n" +
            "8sevenfivetwod5one\n" +
            "fxmhpcdckl5czfcmeight\n" +
            "9216gdptpmninetkfjszftzdfive\n" +
            "ninefivemrvmdt5nshfxgg5\n" +
            "9qclonefive91\n" +
            "six28ninethreefive8two\n" +
            "76five\n" +
            "njdtpktmsqvbfourv9mmonesix\n" +
            "5qxckljjpninedstsfdthreevfrsmtn3\n" +
            "tzrrbjlbq7eight\n" +
            "bzl5\n" +
            "3eightsrnlmlvhtwo\n" +
            "vthqnine1zfive2six6four\n" +
            "cseight1oneone\n" +
            "mgnkflp4grkdrrrtfzmjkbtblfivebgcrmgggxjgkm3\n" +
            "5three1vfrseveneight\n" +
            "seven42seven178\n" +
            "8bnrrzbbvghcqdbtwo\n" +
            "fivegxdzcmbzsix6sktwo2dp5\n" +
            "xqdtmb2sevenxpvdlfsqqkgfxqjqq8468\n" +
            "rscsljnnkd2seven\n" +
            "mzeightwo49ngtzr\n" +
            "threesk3four3five\n" +
            "7shzxkjkgrt71\n" +
            "nxcnnmkqgv1mdmxtkjtwo9bhbbfive\n" +
            "kdxmcg578six7nxqqbm4ddsxzxmtkq\n" +
            "8rjdkmqfivevpfthbjkbt9mnine\n" +
            "5pxfive\n" +
            "hgnfjtwofive2fxxeightmx\n" +
            "pxpqvld69\n" +
            "onesixtxmxttxqfour1rxfrvsgdsveight\n" +
            "95nine9onetwo\n" +
            "48ftnmcxrmxc2vqsgrsqskzs\n" +
            "one4threeseventhree86\n" +
            "one9ninensqxone5zqfvmpd6eightwozgb\n" +
            "527two3croneeight\n" +
            "sixzdzfour291eight\n" +
            "5vzlblhll42hnrrrjj\n" +
            "xzdkkpseven9one1vlsixfour\n" +
            "4tbzbrthree\n" +
            "8hceighthtd\n" +
            "9four4\n" +
            "eighteight7eight6hfthree\n" +
            "6fourbbx1\n" +
            "5onepfzgneightsixxb\n" +
            "xzrjpnfvxr61\n" +
            "two1ninenine6pbhkzzgjq6\n" +
            "sdltwonecbbffldnfdlkh131ggkrqqg\n" +
            "kxrzqltp3vfh39\n" +
            "nine79djhzhhgxvglg\n" +
            "5four1one833\n" +
            "1twosevenseven3three\n" +
            "4nineseven\n" +
            "three42kzqllpf\n" +
            "zkxflrctvsevengkpnqkrrj2\n" +
            "6oneleight9ncnmxbrnkf\n" +
            "qthreenine4vpbzzzfnine\n" +
            "792\n" +
            "hjmn85vtfjgtqv\n" +
            "one3sblncblnvf\n" +
            "ssxxddpqbdznrczqgsix64three4\n" +
            "2four4fourtbeighttmm\n" +
            "fournineeightfive1twofkjcsrklpxlsdvxnt7\n" +
            "lrlzz8eightmpspsk3nineseveneightnine\n" +
            "v4\n" +
            "eight9gfzone\n" +
            "jscpppmpnfkhcxlj1pbtbltmj6one5\n" +
            "8nqrmzrbvzrnine\n" +
            "two34m73twoklqqdlcrrh1\n" +
            "7fourtmpxnf\n" +
            "twocpbznkqnqsixt86\n" +
            "81sevenfsdldftgzvnhhhf\n" +
            "ggntprxxqrpknineeight8fourlmvsr5\n" +
            "sevenztwoseventfour7eight\n" +
            "fkcbvhmqqk1sevenseventwoseventhree\n" +
            "three6ltvtkkhgdpsixsixsltgdngvrttwokz\n" +
            "2fourv\n" +
            "c29fsczzfiveqmrfivejbglcqhl6\n" +
            "4two3\n" +
            "nine2kphnrztjltxgq1sevenone\n" +
            "lpbcgone8\n" +
            "vcznvhllrbfx4275\n" +
            "fhlsdjmppnrgqhqqxt921\n" +
            "4four2sqzzcvh\n" +
            "19nbcvlmhlkqfshhckzkzpqbxfour\n" +
            "seven19\n" +
            "6xprmkgfgntwo4bqk\n" +
            "threexf5threefive4\n" +
            "3fqone\n" +
            "5g2x68cfghcmtwo8\n" +
            "1fourq\n" +
            "pflnjchgnine25one5eightxvjkkxb3\n" +
            "twontnqpcqc17\n" +
            "cxdmgmvmfssevenone6onezdmnltchtnfour\n" +
            "cpcthreeb76zlglhtkdxrlxjsevenzmvd\n" +
            "sixbhjbcpfjeightjcdthzccpzeight1kknxfck\n" +
            "bhkplfzcdqdfsffcone3seven\n" +
            "ninethreeqnxmgmjct2\n" +
            "ninexjlfivelqznkhngnsvnqhqsqdglsix78\n" +
            "9zbqrkmvvnine\n" +
            "1ninehqtmlsd6zjmbgbhjm8\n" +
            "fourvmht91nine551\n" +
            "8eightmfgjteight4one\n" +
            "6eight1lhfhmqvjsixjpdgnjrzzbtbcgb\n" +
            "lxptvkmftqffksixtpfnvkxzvkldfpeightnhncz6\n" +
            "lnsvgtjs2nbsqbkjs\n" +
            "8twohtdv32\n" +
            "9cbdbvvmninekzbrfchsseven1\n" +
            "8onethree7\n" +
            "hk7fourxvqdqmnsdnine\n" +
            "hxbjdsk1vkjbsqn6six3nine7four\n" +
            "485\n" +
            "5four1kmbcxhjseven\n" +
            "2hjfhtmfg3sixonetwo3five\n" +
            "dvfk7sixninethree\n" +
            "onesix827\n" +
            "87seventhree\n" +
            "twosix16lfdfkxbmbcfive\n" +
            "1mssxhvgvmxfoursbjdnbrts27rllfm17\n" +
            "rrvpckn9fourgvrhhzppncrqqml7keightwop\n" +
            "knvmsveightxpbmxptkjbtmzzn3pzbl\n" +
            "47eight1\n" +
            "815vd5gnbgone\n" +
            "xbclfszchvone21\n" +
            "7ttwofourthreehjhpjmtwogrng4\n" +
            "twothreeoneseven9qd66\n" +
            "9dhbgmqgr7threekfhzkqqg\n" +
            "fivekvxpqrkkffc6mjrpksfcqfln9\n" +
            "63two97\n" +
            "txbn163qkbddlcgdznine9\n" +
            "dztphkcfnnninekjqdb89one\n" +
            "mqvtrtz9\n" +
            "7hcnmcs\n" +
            "foursix7nine\n" +
            "sevenstm9gfjvjcnmjnnhbgmrkgkccsflm\n" +
            "two2jgfqdmlkdndmsp1rqlrqonel\n" +
            "eight2qfive1oneqjnine\n" +
            "mtnxzx7tthreeshdxpcrhrk\n" +
            "vzdgktfcq1xtfxqzzfdpng693btkcqhxpsmczbxq\n" +
            "zbvgtnzmlghvhnklhmhjnxckone4six\n" +
            "98eight2seven3hhbxgvnhbg\n" +
            "seventwo7seventhree5ltlptmhjp\n" +
            "1rf75fivegx\n" +
            "2nineonemlhxmhdt7six3\n" +
            "nine6sevenlzndhbnpkxdhdtcqpzgvkskvjkhphpqnxl\n" +
            "qnqpnlxcjr3phkkpnccxr2sixrslhrtf2\n" +
            "12mrkvqsjdcc47six\n" +
            "onehhdveight35jgnmgvqgxdr\n" +
            "hgoneight5\n" +
            "m9eight384eight1\n" +
            "1p6\n" +
            "3sixnine41seventhree4\n" +
            "5dvssdf\n" +
            "blchhcfourgzvssbhqdxdbxt14zvbknhnll7\n" +
            "7twotgqrxddm5\n" +
            "btlkbgbtwotwo5\n" +
            "five63ninesnqx\n" +
            "fivemkvjpslfoursixfivepjvtx4\n" +
            "74threeeighteight6cpbxbqgzh\n" +
            "twoeight7bh\n" +
            "rgtwo7fnck7\n" +
            "five4sixnvjtcmx12one\n" +
            "ghqgdfour33\n" +
            "tjpdztkfour666dxgzjzlgnz\n" +
            "ninegnqrqpbrz8seven7sevenhfbone\n" +
            "npzlpklnvgone6nrjcpz8\n" +
            "2seven6m8\n" +
            "seven3fivegqvxgrjcnine2xppl\n" +
            "nbmvdgk9grz4\n" +
            "four291\n" +
            "tdnfgkzkxbfpkpcthreenineoneone1\n" +
            "7nineflqptxmdjgttpll\n" +
            "one1jnhcvthree1\n" +
            "foureightkxfcqlkp2fclpr8bzxtfbl8grdsntkrst\n" +
            "six16fivezqbchmjbb\n" +
            "zjhkd5two8\n" +
            "745shv\n" +
            "l64dqvsixthreethree\n" +
            "rffrrmjsfj2jblgqnl7gjfcqtszfour7\n" +
            "fcqcmchhc7t\n" +
            "twofour834ninefpvbvps\n" +
            "gmhhjr94svpddnmxvd98threerlljccvq\n" +
            "ninetwosevenb71three\n" +
            "eight4xllkpmjkrp4bv\n" +
            "zhvzsfourrkflmjpjhfourfjbd32jkvrpzqg\n" +
            "2frgbkngmsix9stldncmsczh\n" +
            "eight9three42grlbfps85\n" +
            "1lrshxpgxlsnrlfjlxk2\n" +
            "jfhmhcml8mvbfkxhmoneeight9\n" +
            "five8sevenlzvpzpsbjfourseven1fkcfdf\n" +
            "4vmldcjpbbsnfourseven4three\n" +
            "mfchhbqk7bdlrqhone2fiveone\n" +
            "hnncfrgmnkg5six\n" +
            "dbone55seven\n" +
            "geightwoonevhxbqbpfkx6two67\n" +
            "sixcrnq1hnrsttfxvjeighteighttwoone\n" +
            "fiveonetwo7six\n" +
            "9nqrmt5n9fkpbhd7\n" +
            "two1fivesixtsrq\n" +
            "684\n" +
            "ckbxntxfhthreefour7sixseventwo\n" +
            "stdhzqdpnxnine6tn7kjxftfbksevennhfxznjxgchm\n" +
            "8czxhfptlknjlhn5clhzdfgntx741\n" +
            "3nine64vvgsfour61pzb\n" +
            "rloneight7lfrfqqb8fivefour3\n" +
            "vnhbtkbqone4sixsevennmrgmmptvreight4\n" +
            "bdvjp354992jgfhzzvhv\n" +
            "fourp1\n" +
            "five7oneseven\n" +
            "oneone954threefivesixsfr\n" +
            "sixfivevmzlzdfjvq5\n" +
            "4bs\n" +
            "threetwo64ccks3\n" +
            "onetxqh3ljpnkr9onegsmkq\n" +
            "five24seven6threethreezfqzgzjztgntkcfzt\n" +
            "3fourv2\n" +
            "eightoneeight6qseven47seven\n" +
            "559ninexcdkqvszsq1\n" +
            "95sixthreetwo8fourthreesix\n" +
            "ksxtrn1gqxthvxjltfivejpmgvz8\n" +
            "ninezdkfvgceightnine7sevenfiveeight1\n" +
            "h43zktkckcjrg5nmzjkrzmjqsix3\n" +
            "44pqlgmmzvgzpslmnccdjlvq\n" +
            "4threefoursix87\n" +
            "92gnjfsxzlcn71qzcbvq6nhmgsvmbrvvjzqlndhl\n" +
            "hkmjkc9fourpbgjlvqxhbhnzvmlnfrqsixsixksix\n" +
            "mspbpsgzn31ninesix\n" +
            "7xqtttthreegr4fourrbflxfznfs5three\n" +
            "rtpknqgsix7sixthreethree1one\n" +
            "qqlqh8seven\n" +
            "six11eightkh73one\n" +
            "eight9mjzpmhcr999fourfive\n" +
            "fzeightwo7smqq\n" +
            "7dzzxnttq\n" +
            "4vfk9\n" +
            "ninermjmpprxmsdgrpgzmmqtjxkpfour5kscxs\n" +
            "h5lnhnrqhvltpsns\n" +
            "twosfdsxcjjhg871755\n" +
            "1one5\n" +
            "933zdzz1five2\n" +
            "4zxh9j\n" +
            "bnlmdd9\n" +
            "nine4xchhpgnfjtwohggvlkkxthznnf7four\n" +
            "3foursixhmsddvmqkgpjvone34\n" +
            "bjfxjlseventhreeninesevenfivethree9\n" +
            "qhqgxtjvslnvbvjsixjplmfq8\n" +
            "8ffjpthreerzkdjkjjzxvqkspsevenfive\n" +
            "3three4two1\n" +
            "fiveldkk7ninesevenmfnjfjmdgeightprjrq\n" +
            "4rqbz6eight3lbgbpgcveightthreefive\n" +
            "sixdsmvltdv2six3fourxtkzsvjdbvqfmthree\n" +
            "3one2xgzvczlxvfdpjqgninefourfourzft\n" +
            "sixcnfznvcb8four\n" +
            "3threethree\n" +
            "trzqdpslthree8\n" +
            "3fivefourninefivethreefive8nine\n" +
            "1sevensevennineninezmghprscjskqppgmh\n" +
            "6zfoneqkxhxmtwofour3four9\n" +
            "twosix6dxftmjgclkkmzxmkglmqvsrtjcp\n" +
            "ninejkbk8v5fivefivethree\n" +
            "9twoneqv\n" +
            "1cq51lklfoureight2\n" +
            "8sixfournine3one\n" +
            "5plgtszkt6856six\n" +
            "qoneqjph11hgvhhkglsreight1pkxrltrzm\n" +
            "nine25mlxmkmcg4xlrntfsrrxmlhdtzt1\n" +
            "fivetfdzmsq2\n" +
            "pdhnkbjrj5fiverjpgmntqkpmx\n" +
            "fourvgc1msdnxrbpbcjfive\n" +
            "14tbcfmjl3sevenvj\n" +
            "ninezrcfqvg9\n" +
            "5eighteightkkvtsbrkjlthreegspdm\n" +
            "99four5two9\n" +
            "pvlvjvhmg5krzl149sixtknbgfsgvf\n" +
            "44tvzgpz1\n" +
            "8threenmhmptmshpcsix\n" +
            "5rdjmjnmkcd\n" +
            "ctwo6\n" +
            "two1dhtmsdtsds\n" +
            "ndjd4sbzm5fourseven82\n" +
            "rfqsxkdhcr1twotwo\n" +
            "4qrt5threetwosevenffjdvtzhgfd\n" +
            "6421\n" +
            "sjgfshzjg5four\n" +
            "threeqpvpvdhgjhpgqxsrhhp5dqjqlr\n" +
            "five7ncchvpcfmglmfzstrmvhfnqndzrmvb5\n" +
            "fvnfmcrh684bjq63dxnnlznrn\n" +
            "threedccxvrtbj62bfqfzlpxms8five\n" +
            "893shxkgpvpfour36nine7\n" +
            "dtoneightbrmthree6\n" +
            "6seven58nine1mgqqtzfsszlrgghmlknx\n" +
            "four64\n" +
            "five5dklfour4\n" +
            "lgv2eightvcp\n" +
            "pnfkrfnncv3lgqlrznone\n" +
            "sgcthreegxrnfkpb731\n" +
            "8twothreetnxlmjtwoneb\n" +
            "txkrmcklpdhclrklxz41lhddmkp\n" +
            "rqndtwosixq8\n" +
            "btbndntqsllxc6vzfrdqm2sixfiveeight\n" +
            "rhvfourp1seven5cxcc\n" +
            "jlzzqkvfxqltgbnj1\n" +
            "24szksixthreeone62\n" +
            "2fourfpmjltjnqvgrgxxbggtseven6qms\n" +
            "78prqkfbf6sevenfivesixeight\n" +
            "drtwoszsevenckqrxfseven3sixseven\n" +
            "zbsj6four\n" +
            "hrcxgvdbd6\n" +
            "six9three4onefournnsxgvjtrdthree\n" +
            "441\n" +
            "fjnjksnvgjznxflonetwovcnmvhdgjfggfvxmmg2hppfcgjqv2\n" +
            "kjszbvrcqznbf4eight5four\n" +
            "twolmbrdmx8kpltmqznslfsixsix\n" +
            "6bjrfthk8\n" +
            "gmzzsthreensrx3\n" +
            "sevenz63xlscxeight\n" +
            "fivehmrcphp7nine53\n" +
            "fivepmqvjqllgthree5vkpn94nine\n" +
            "seventhree9sbklvfvpsixr6\n" +
            "one56six\n" +
            "pfivetmqrbqxccpxsbcc87five8\n" +
            "mtmnvlhfsix75ppk9rrqzbbplmbseven\n" +
            "547mmntlxflkztkkftxkrrk\n" +
            "5four9threelcqlsrlvg2\n" +
            "gglpjhvjnnnrcbj3n55\n" +
            "xgdbjcrxdf5jjdfrrkzkdzpjkrlstwogbzcjq\n" +
            "cfmgxkjcfq9bkcpkrpltp\n" +
            "fcqkjhqgpkthree4sixthree84frmfqqkrs\n" +
            "onetwosveight68ftgjft3four\n" +
            "jvlmg2eight3bdptwo4sixseven\n" +
            "three1bhdkfnvt\n" +
            "6eight12fiveseven\n" +
            "onedbxgcqnltfour35\n" +
            "sxtwone5336psninexnrjsxsix\n" +
            "four79one47jvmmhhggcthreecgkxhnlm\n" +
            "17eight2fivetzcfmrlxvd\n" +
            "rxlhkjlm778oneone\n" +
            "8one1one499nine\n" +
            "six2fqd\n" +
            "9smpkfchhzn8seventrpbvcssscseven\n" +
            "nbmqctcldmnvnbnzns9twofive2three\n" +
            "1five1two\n" +
            "89brvbgnine\n" +
            "vcbrztfjzn4\n" +
            "4fvmlvxjd\n" +
            "lsixoneplt7two9\n" +
            "kphbsssvsnjgjnvqjcbh2nkmfeightseven\n" +
            "three4xsrmfldqgpqxbpsevenfour\n" +
            "rzd8xzmcdch\n" +
            "bjffone41xzone\n" +
            "xkmhqhgr2lxpv4jnsrnfour\n" +
            "31cplcztdkhsix\n" +
            "6tkzzqqckvdlkxrfourrveightwoch\n" +
            "26vkvbdvggfcsjccrkzbh\n" +
            "3nr\n" +
            "ninefourklmqgsix3cvnr\n" +
            "mlnzksvhnvvbxpsfnspl6hpqkdmg\n" +
            "btwone1jpgjdmgbfive\n" +
            "817sixqtvhxpfglj5kzmbtwofive\n" +
            "1tworcsevennine\n" +
            "xseven69six11\n" +
            "four3sevenjmgqzf3two\n" +
            "mbrfzsj2\n" +
            "8xgsdninefourseven\n" +
            "six14snscgfnconeeight4\n" +
            "seven4fivefoureightfive1\n" +
            "threegjgdnqvhqlbdv24fivexdvpdthree\n" +
            "9ldkmtzghbtwohqzzntwofive\n" +
            "fourxh8\n" +
            "eightfkxhflcone3xscqdqqkrk\n" +
            "qzlbtgc2sevens7\n" +
            "rfjgmfbjt185hztszz111\n" +
            "pxsixssnfgtfour9\n" +
            "zxflhgjnmbgfdqtzs4twojzxbrsix\n" +
            "7cc153fivel8\n" +
            "bzoneightlrvmnrh98\n" +
            "threetwogd6bhdkrjhxt2three\n" +
            "hlrscbd8rvppfclqdtseven\n" +
            "twofivelbjh3gbnbdbpthtgpqjmxjlmzjq9zqll\n" +
            "2fczpbhqjqfgzvzzkqgmsevenone58three\n" +
            "fourzvmlt3sggpjzssljc8twoeighttwo\n" +
            "ninescglkgftppbm187\n" +
            "five1vll26two\n" +
            "czghbj5827\n" +
            "nine7threerngqxk\n" +
            "four5bjbhfglffourseveneightfourj8\n" +
            "djqrxfive4five8\n" +
            "3xzhpqc6six\n" +
            "1htdxrgtrhvpgz\n" +
            "5bkxxsccdftjmhkfjqvjzjnine\n" +
            "pxpdfdnnpqzspxd9xrpvrxhnsix9four3\n" +
            "gtxlzxdninexxhseven5\n" +
            "xcdkvdg7nineeightsdjvkhzgmone\n" +
            "zrnrrpxdfcnine2qgjxzfxcqgghbdk9\n" +
            "twozrckqbppsixhh7pmrmnktnrb7five\n" +
            "tdxpjz2kccgqzcslm8sixsixtwo\n" +
            "8tgcb32\n" +
            "eight391gxm99five8\n" +
            "one3fivegrpjr4trqxj5eighteight\n" +
            "7eightzsnndnine8fourgphhbhxn\n" +
            "7five8seven6mhkksix\n" +
            "8jvccfldpqfourgltcqbkpkfourtwohbvnnine2\n" +
            "rrvmvtvbrmsgnstbghfl28\n" +
            "66fourninekjzfzrj\n" +
            "seventwoninethree3plvfoureight5\n" +
            "fmpzrfpqqbfivenine7\n" +
            "nrkbbdqdthree1fkbfivefourqlksbfdsjtthplhjhlvgh\n" +
            "176seven\n" +
            "3fourfiveseven681\n" +
            "five88rzxk3mqgtkvgpdx\n" +
            "pgttnnvnhtl4rljpqjzhphmkztwokdqspbth\n" +
            "54eightgngggmdmnxgd\n" +
            "d6jnkq78cgvkrgseven\n" +
            "sixeight7eight1dmvvprm\n" +
            "72twotwo2kntsrccqkmzbn4\n" +
            "snctbphhl2jgpghbvhg\n" +
            "one5xxvhfive6twozmlxddppmb\n" +
            "145eight5jcpmqhkpgrdbvlzl3\n" +
            "two4vtlfddtzrzlmkgx15\n" +
            "2fourseven9pxqzdf3\n" +
            "6ninec3\n" +
            "ninefsix54\n" +
            "sevenbzgrdbbvfmbkvb8\n" +
            "vntfxdprf91rmgvxlxhntsztmggjr1\n" +
            "six4spdffrjfthree595four\n" +
            "pxfftjkdnninexkjvskrtpmjkhnncflz26\n" +
            "dkjmxmhpc7eight7\n" +
            "hsbdfeight9hhrjcn8twothreehjpnbhslcc\n" +
            "437kzcqvsmxkknfour\n" +
            "8twoone54sixvmlcjdnrgnqbmlrvdtnh\n" +
            "one587\n" +
            "4kxxsrcseven33dcvbbgkbcd4fourfour\n" +
            "nine56\n" +
            "oneeightpz4rqbrcdvjbx55\n" +
            "threefive33ninexrlj\n" +
            "3bxjdxlmlgs\n" +
            "gqmkpqpppfour9fouroneeightseven\n" +
            "492\n" +
            "one398threetwo6dseven\n" +
            "j8vlfrninebdgnineljtvbeight\n" +
            "nnnhx28sixtwo\n" +
            "fiverbgztggr6ktrsfvbtqlbtdshqjxjhj\n" +
            "qmdjfthzfour318hrffjj\n" +
            "977dpssrfgfxfxkk6\n" +
            "rvklzfdfour3twofour8five\n" +
            "czbjbfdcbs1rgkfscgntmhksixhqgbrmzvzrg\n" +
            "3xqlbqbcxnfq\n" +
            "six29\n" +
            "jhnfthree7\n" +
            "five1821\n" +
            "578blhpbtrjthree83qtflsj\n" +
            "fgzqnrvfcqkfrdmgkndmrxfctgvsbfive2eight5\n" +
            "feight8eight\n" +
            "3qmfbdztrgpb5\n" +
            "ck5three14lzmffcljxcr\n" +
            "3twoqgjqlvjeight5nddhpflj1\n" +
            "vvdsttjjjgnrzgfournkkhp622onesix\n" +
            "two7seven6\n" +
            "7941\n" +
            "28two7\n" +
            "ninejhxnjctz3jtxmlmjg\n" +
            "vmjpxvqg24pzjfsxvcg5seven2\n" +
            "xpqbffpvmn5\n" +
            "32eightseventhreekqdgtcxgjxvv1seven\n" +
            "2eight3tllbkklghb7\n" +
            "sevenfour1\n" +
            "tjsjfldclvqq1sxcl\n" +
            "mrdqvsxk15jbxstdph\n" +
            "9fivefivebbtcvhqjjdvvqeight\n" +
            "fourdtbkzvhrbvzqnnzghnpv1231\n" +
            "bz34five1\n" +
            "six26two2\n" +
            "bczkffnrtmsrctwoninelbnxoneeight2\n" +
            "sevenstvffmtkqqxg57hthreeeight\n" +
            "4fivesevenrdfcdrxd4\n" +
            "bbbrjsjrmn8px\n" +
            "317vncvpdrh91threetwosix\n" +
            "9sevenzpfivethreefivenineseven7\n" +
            "twodsnvkbvfbtwo62tt6\n" +
            "threesctkeight3vdjrnflh9nckgmzhdf4\n" +
            "eightsixtwo39skhnzf\n" +
            "foursix6\n" +
            "3sixzp5fdzjv\n" +
            "ntwone9xzspfhrthreehsgpqdone62\n" +
            "five9597tgrfbl9\n" +
            "six4rvrcbbjzfdcgctsxjxmjrpc4thmmj8\n" +
            "3sixmdglgdj2zzrkgsdgk2\n" +
            "cbfxpgftninekthreexvmhxmkx1fourf\n" +
            "76twoone\n" +
            "7six32two1fivefspjtdsix\n" +
            "nrcntbgdtjsevenztsmsgfmfour9thslsmhgnk2three\n" +
            "21ltslbrnineseven7\n" +
            "41\n" +
            "sevencdsnmzkspseven49\n" +
            "jbzkthreebjgvhfhcftwojbzdbmcdlff29\n" +
            "sevengjlph11fivexhzdrs\n" +
            "fzkznzxgbsfq4\n" +
            "gvpqjgrfdbdtrpqseven11mmjpkz5\n" +
            "ksfjpnchqzqone15eightsixfivenine\n" +
            "2skjmpvdfoursixtwones\n" +
            "dmtzhqfivethree3eighteightoneseven\n" +
            "one6fourrrrtkkjvr\n" +
            "229spkrxlg\n" +
            "4xjqzfourdtmq\n" +
            "mkv5six\n" +
            "8jdzlpqvc89two\n" +
            "2foursix69k\n" +
            "xbqrmktzfive4\n" +
            "five9rjrvcpfbseightfkmlgbvqkbqj\n" +
            "qnmkvkmckfxqmdtwosevendj6sevensixfive\n" +
            "mkdvknghvsgzrbbjqngbsqeight6mjxfivenineq\n" +
            "6two97mxm\n" +
            "two26jjqjs\n" +
            "1scslcns\n" +
            "pckdk4onesevenpnxq8lxxbzvftcbeightl\n" +
            "qczvprdbeight3twosixsevenfivenbzj\n" +
            "462mfgmhfseven4vmv\n" +
            "gqsrhltninethreedbkrjdfivetwo1\n" +
            "ppsix99nine8qvhbnn48\n" +
            "nine35fxlxqfctwonezf\n" +
            "four2twofive1\n" +
            "847dsgonethree1vkmhmtv\n" +
            "8gnfbqmzszxdfkv5five\n" +
            "22kvqd\n" +
            "five1sevenl59\n" +
            "kgshxdjdfjqzthhplhjqxbjpbxggtz1\n" +
            "fourbzbzvtfj8twoone6629\n" +
            "hn28six1\n" +
            "xqxknfivevxhljqpsixtwo3\n" +
            "hsconethree1fourthree\n" +
            "three5gnlgcthree36rkvlpkcvronefour\n" +
            "rvjqkndonenine3hbrtlzhcbfbkcfive\n" +
            "hhrmnbnct6rdxxtkxkcrbdfg5\n" +
            "6xsqkbthreerjgbzfhb\n" +
            "sixnlxzmblfzx5cspjqthree\n" +
            "4twondrxjb\n" +
            "4three6b\n" +
            "4four3three16\n" +
            "eight3hshdzptsq6twosfour3\n" +
            "eight37twotrxvpxk2ksbldctj\n" +
            "fourseven8fkmtqzdbfourseven\n" +
            "6vngvcmplx\n" +
            "jhr6gfplmzpr2fourfive\n" +
            "eightnine49twoeight2nfndmmb\n" +
            "three7threej4xnffjtnckltwo\n" +
            "onegzlnjsgzlg82mkbfhtmhfour\n" +
            "85vnseight5fivevcqrgvgrtp\n" +
            "47chxx6pkrdxvmrvvfxbl5\n" +
            "34ctkstrjxsnfourseven\n" +
            "two9zcrghthreethree\n" +
            "veight37\n" +
            "two44nine449\n" +
            "58eight98cspxfhftvx\n" +
            "cxpththree7pbmhhmkfzfvthree\n" +
            "8nine2hbmdnvbthree\n" +
            "1four6ncdvzqjqhx1\n" +
            "1bgqspl958lrj\n" +
            "7nvmqrnthreejbzgnzvzpgkr69\n" +
            "7576threesix\n" +
            "twoc83pt\n" +
            "fourkdnsvcq9sevendmhsdgt54threej\n" +
            "zrjts8sixsix237flm\n" +
            "8eightrndfour\n" +
            "two9jsix5gcxf\n" +
            "fivefour7nineseven1qtcdqbp1four\n" +
            "fourzvkqhdninetwoftscrmsd64nxsgx\n" +
            "q1tdsskthree\n" +
            "mkhttggvjh9ctzffdqdjnheightninegmxqxhqrfqgbgzt\n" +
            "ninep2fourf\n" +
            "fiveeight2zxjpzffvdsevenjhjvjfiveone\n" +
            "15737seven\n" +
            "pdrss6oneone4fournine\n" +
            "7b";

    public static String exempleDay1 = "two1nine\n" +
            "eightwothree\n" +
            "abcone2threexyz\n" +
            "xtwone3four\n" +
            "4nineeightseven2\n" +
            "zoneight234\n" +
            "7pqrstsixteen";

    public static String day2Input = "Game 1: 5 red, 1 green, 2 blue; 2 green, 8 blue, 6 red; 8 red, 3 blue, 2 green; 6 red, 1 green, 19 blue; 1 red, 17 blue\n" +
            "Game 2: 4 red, 5 green, 2 blue; 7 red, 14 green, 3 blue; 2 green, 5 blue, 11 red; 10 blue, 3 green; 9 green, 6 blue, 13 red; 7 red, 5 green, 9 blue\n" +
            "Game 3: 9 green, 18 blue, 1 red; 6 red, 10 blue, 5 green; 4 blue, 4 red, 15 green\n" +
            "Game 4: 1 red, 13 green; 10 green, 2 red; 3 red, 4 green, 2 blue\n" +
            "Game 5: 4 red, 2 green, 1 blue; 4 red, 9 blue; 4 green, 1 red, 6 blue; 3 blue, 2 green, 6 red; 5 red, 4 green, 1 blue\n" +
            "Game 6: 6 red, 3 green, 6 blue; 3 green, 5 blue, 12 red; 3 green, 9 blue, 3 red; 13 red, 8 blue\n" +
            "Game 7: 3 blue, 1 red; 3 blue, 10 green; 4 green, 5 blue\n" +
            "Game 8: 11 green, 4 blue; 4 red, 4 blue, 11 green; 4 green, 3 blue; 1 blue, 6 red, 12 green\n" +
            "Game 9: 1 blue, 4 green, 1 red; 5 green, 3 blue; 9 green, 4 blue; 3 blue, 1 red, 10 green; 6 green, 2 blue\n" +
            "Game 10: 5 green, 6 red, 7 blue; 7 green, 5 blue, 5 red; 8 red, 6 blue, 8 green; 2 blue, 8 green, 6 red; 6 blue, 8 red, 4 green\n" +
            "Game 11: 1 blue, 10 red, 10 green; 11 green, 2 blue, 16 red; 4 blue, 7 red, 14 green\n" +
            "Game 12: 8 green, 9 red, 12 blue; 2 green, 4 blue, 7 red; 1 red, 9 blue, 7 green; 8 green, 2 red, 10 blue; 1 green, 5 red, 5 blue; 6 green, 5 red, 1 blue\n" +
            "Game 13: 3 green, 1 blue, 6 red; 1 green, 10 red; 1 blue, 15 red, 2 green\n" +
            "Game 14: 2 green, 6 blue; 1 green, 2 blue, 2 red; 5 blue, 1 green, 2 red; 4 green, 5 blue, 4 red; 4 red, 5 green, 4 blue; 1 red, 5 green, 6 blue\n" +
            "Game 15: 12 green, 7 blue; 19 green; 11 blue, 16 green, 1 red; 1 red, 2 green, 3 blue; 8 blue, 1 red, 19 green; 14 blue, 3 green, 1 red\n" +
            "Game 16: 2 green, 13 blue, 3 red; 5 red, 12 blue; 6 blue, 8 red; 4 red, 1 green, 4 blue; 1 green, 15 blue; 4 blue, 2 green, 1 red\n" +
            "Game 17: 11 blue, 7 green, 2 red; 12 red, 8 green, 8 blue; 2 red, 6 blue, 6 green\n" +
            "Game 18: 1 green, 2 blue; 2 green, 1 blue, 4 red; 3 green, 16 red; 2 red, 3 green\n" +
            "Game 19: 11 blue, 3 green, 3 red; 11 blue, 5 green; 3 green, 3 red, 8 blue\n" +
            "Game 20: 1 green, 6 blue; 4 blue, 6 green; 1 red, 10 green; 12 green; 5 blue, 1 red, 4 green; 1 green, 5 blue\n" +
            "Game 21: 7 green, 3 blue; 1 red, 5 blue, 6 green; 1 red, 11 green; 8 blue, 1 red, 10 green; 1 red, 5 blue, 3 green\n" +
            "Game 22: 3 red, 1 blue; 3 green, 1 red, 1 blue; 7 green, 2 blue\n" +
            "Game 23: 12 green, 1 red, 2 blue; 10 blue, 1 green, 1 red; 9 blue, 8 green\n" +
            "Game 24: 5 blue, 6 green, 6 red; 3 blue, 1 red; 8 blue, 2 green, 12 red; 1 green, 2 blue, 14 red; 2 blue, 5 green, 15 red\n" +
            "Game 25: 6 red, 13 green; 1 blue, 1 red, 3 green; 1 blue, 12 red, 10 green\n" +
            "Game 26: 16 red, 2 blue, 7 green; 1 blue, 7 green, 8 red; 1 blue, 3 red, 9 green\n" +
            "Game 27: 4 blue, 15 green; 6 green, 2 blue, 1 red; 9 blue, 10 green, 4 red; 3 red, 3 green, 6 blue; 11 blue, 7 red, 11 green; 6 red, 5 green, 13 blue\n" +
            "Game 28: 10 blue, 8 red, 10 green; 4 blue, 11 red, 6 green; 8 red, 9 green, 10 blue; 4 red, 9 green, 2 blue\n" +
            "Game 29: 4 red, 9 green, 7 blue; 10 blue, 6 green, 4 red; 1 green, 2 red, 10 blue; 3 green, 9 blue\n" +
            "Game 30: 6 blue, 9 green, 10 red; 6 blue, 4 red; 5 green, 2 blue; 5 green, 2 red, 2 blue; 6 blue, 8 green\n" +
            "Game 31: 7 blue; 2 green, 6 blue; 1 red, 9 blue, 5 green\n" +
            "Game 32: 8 blue, 2 red, 4 green; 6 red, 2 blue, 1 green; 14 blue, 8 green, 8 red\n" +
            "Game 33: 1 green, 1 red, 1 blue; 2 blue, 1 green, 12 red; 1 green, 1 red; 1 blue, 2 red, 1 green; 7 red, 2 green, 2 blue\n" +
            "Game 34: 3 blue; 2 blue; 10 red, 1 blue, 1 green; 5 red; 1 green, 1 red, 1 blue; 1 green, 2 red\n" +
            "Game 35: 10 green, 1 red, 16 blue; 4 red, 10 blue, 9 green; 1 green, 7 blue, 5 red\n" +
            "Game 36: 1 blue, 3 red, 16 green; 1 blue, 3 red, 1 green; 9 green, 3 red, 8 blue; 14 green, 6 blue, 3 red; 3 red, 12 green, 4 blue\n" +
            "Game 37: 11 red, 3 blue; 15 red, 8 blue, 6 green; 6 green, 19 red, 11 blue; 1 green, 4 blue, 14 red; 12 blue, 5 red, 8 green; 4 blue, 9 red\n" +
            "Game 38: 4 green, 10 blue, 3 red; 1 green, 1 red, 11 blue; 2 red, 12 blue\n" +
            "Game 39: 3 green, 1 red, 4 blue; 9 green, 1 red, 18 blue; 4 red, 4 green, 17 blue; 4 red, 10 blue, 14 green\n" +
            "Game 40: 5 red, 4 green, 8 blue; 1 green, 9 blue; 9 blue, 3 red, 6 green; 8 red, 9 blue, 9 green\n" +
            "Game 41: 1 blue, 9 red, 3 green; 9 red, 10 green, 15 blue; 13 red, 8 green, 8 blue; 19 red, 6 blue, 2 green; 7 green, 5 blue, 12 red\n" +
            "Game 42: 15 blue; 1 red, 1 green, 9 blue; 6 blue, 1 red; 1 green, 4 blue\n" +
            "Game 43: 1 green, 8 blue, 2 red; 1 red, 1 green, 6 blue; 7 blue; 7 blue, 3 red, 1 green; 2 red, 5 blue\n" +
            "Game 44: 7 green, 11 blue, 6 red; 9 green, 8 blue; 4 red, 15 green; 12 green, 14 blue, 8 red\n" +
            "Game 45: 4 red, 4 green; 14 green; 4 green, 2 blue; 1 blue, 12 red, 5 green; 3 red, 6 green; 11 red, 1 green\n" +
            "Game 46: 2 blue, 1 green, 1 red; 1 blue, 6 green, 1 red; 2 blue, 1 red, 1 green; 5 green\n" +
            "Game 47: 1 blue, 1 red; 14 red; 3 green, 2 blue, 17 red; 4 green\n" +
            "Game 48: 1 red, 11 green, 2 blue; 1 red, 11 green, 6 blue; 13 green, 1 blue, 3 red; 3 green, 4 red, 6 blue; 12 green, 5 blue, 1 red; 2 red, 4 green, 4 blue\n" +
            "Game 49: 5 blue, 3 green; 2 green, 8 blue; 5 blue; 4 green, 5 blue, 1 red; 4 green, 7 blue; 1 green, 3 blue\n" +
            "Game 50: 3 red, 5 green, 2 blue; 9 green, 7 red, 4 blue; 3 blue, 6 red, 13 green; 6 blue, 8 red, 9 green\n" +
            "Game 51: 2 green, 11 red, 7 blue; 5 blue, 13 red; 1 green, 2 blue, 3 red; 6 blue, 8 red; 11 red, 2 green, 4 blue\n" +
            "Game 52: 15 blue, 1 green, 4 red; 4 green, 10 blue, 2 red; 6 red, 18 blue, 1 green\n" +
            "Game 53: 2 red, 10 green, 6 blue; 4 green, 3 blue, 3 red; 17 blue, 19 green, 5 red; 6 blue, 6 green, 9 red; 5 blue, 17 green, 7 red\n" +
            "Game 54: 9 blue, 8 red, 6 green; 6 red, 8 green; 1 green, 6 blue, 1 red; 5 red, 4 green, 9 blue; 5 blue, 2 green, 5 red\n" +
            "Game 55: 8 blue, 8 red, 10 green; 3 red, 4 green, 9 blue; 4 red, 3 green, 7 blue\n" +
            "Game 56: 3 red, 6 green, 1 blue; 5 green, 1 blue, 1 red; 1 red, 2 green; 10 green\n" +
            "Game 57: 1 green, 4 blue, 12 red; 17 red, 7 blue, 10 green; 17 red, 5 blue, 3 green\n" +
            "Game 58: 1 red, 5 green, 14 blue; 5 green, 6 red, 7 blue; 4 blue, 8 green; 3 red, 9 green, 7 blue; 8 blue, 8 green, 6 red; 8 green, 7 blue, 5 red\n" +
            "Game 59: 3 green, 5 red; 2 red, 13 green, 1 blue; 19 green, 1 red, 1 blue; 19 green, 1 blue; 18 green, 1 blue, 5 red; 6 red, 9 green\n" +
            "Game 60: 5 red, 1 green, 6 blue; 8 red, 6 blue, 14 green; 8 green, 8 red, 3 blue; 2 blue, 5 green, 3 red; 4 blue, 1 red, 14 green\n" +
            "Game 61: 7 red, 4 blue, 2 green; 2 green, 8 red, 9 blue; 5 blue, 2 green, 8 red; 8 red, 1 green, 8 blue\n" +
            "Game 62: 6 red, 3 blue; 1 blue, 2 red, 2 green; 3 red, 1 blue\n" +
            "Game 63: 2 red, 1 blue, 2 green; 1 blue, 1 green; 2 green, 4 red; 3 green, 2 red; 2 green\n" +
            "Game 64: 5 green, 6 blue, 7 red; 2 red, 5 green, 8 blue; 7 green, 9 blue, 1 red; 4 green, 5 blue; 19 blue, 5 green, 13 red\n" +
            "Game 65: 3 red, 1 blue, 4 green; 5 green, 3 blue; 9 green, 1 red, 10 blue\n" +
            "Game 66: 6 red, 13 green, 2 blue; 2 blue, 5 red, 9 green; 18 red; 2 green, 1 blue, 1 red; 19 red, 10 green; 1 blue, 15 green, 13 red\n" +
            "Game 67: 8 blue, 3 red; 1 red, 12 green, 7 blue; 4 red, 6 blue, 5 green; 11 green, 10 blue, 7 red; 5 red, 9 green, 14 blue\n" +
            "Game 68: 1 red, 3 green; 10 blue, 1 red, 3 green; 1 green, 17 blue; 16 blue; 6 blue\n" +
            "Game 69: 11 green, 5 blue, 8 red; 2 red, 5 green, 1 blue; 10 green, 2 blue; 11 green, 7 red, 4 blue\n" +
            "Game 70: 2 green, 1 blue, 13 red; 16 green, 20 red, 4 blue; 10 red\n" +
            "Game 71: 10 blue, 6 green, 7 red; 5 red, 5 green, 2 blue; 7 green, 4 red, 5 blue; 1 red, 8 blue; 5 red, 1 blue, 8 green; 5 blue, 1 red, 5 green\n" +
            "Game 72: 2 red, 4 green; 2 green, 2 red, 1 blue; 3 blue, 3 green, 2 red; 2 green\n" +
            "Game 73: 5 red, 19 blue; 12 blue, 4 green, 16 red; 14 red, 11 blue, 1 green\n" +
            "Game 74: 2 red, 1 green, 9 blue; 5 blue, 1 green, 2 red; 2 green, 1 red, 13 blue; 2 green, 1 red, 3 blue\n" +
            "Game 75: 7 blue, 1 red, 18 green; 17 green, 8 red, 13 blue; 15 blue, 4 red\n" +
            "Game 76: 1 green, 12 red, 13 blue; 5 green, 11 blue, 12 red; 10 red, 1 green; 10 red, 2 blue; 5 red, 2 green; 2 green, 17 blue, 3 red\n" +
            "Game 77: 2 blue, 1 red, 1 green; 7 red; 7 red, 3 blue, 2 green; 10 green, 1 red; 3 red, 7 blue, 6 green\n" +
            "Game 78: 10 red, 2 blue, 2 green; 1 blue, 6 red, 4 green; 12 red, 8 green; 6 green, 8 red, 7 blue; 11 green, 5 blue, 6 red\n" +
            "Game 79: 7 green, 5 red; 6 blue, 2 green, 15 red; 9 blue, 2 red, 12 green; 1 blue, 4 red, 10 green; 4 blue, 12 green, 11 red; 5 green, 3 red, 5 blue\n" +
            "Game 80: 1 green, 13 blue, 2 red; 2 red, 1 green, 13 blue; 7 blue, 8 red\n" +
            "Game 81: 1 green, 2 red, 11 blue; 5 red, 3 blue; 1 green, 1 red; 14 red, 1 green\n" +
            "Game 82: 12 red, 3 blue, 8 green; 15 red, 9 blue, 8 green; 6 blue, 13 red, 8 green\n" +
            "Game 83: 4 blue, 6 green, 3 red; 7 red, 2 blue, 9 green; 6 green, 3 red\n" +
            "Game 84: 4 green; 3 red, 3 blue; 4 red, 1 blue, 2 green; 1 red, 5 green, 5 blue; 1 red, 5 blue, 3 green\n" +
            "Game 85: 3 red, 4 blue, 15 green; 9 green; 2 red, 4 blue, 6 green; 1 red, 4 green, 7 blue; 3 red, 10 green, 9 blue; 1 red, 13 green, 3 blue\n" +
            "Game 86: 8 red, 6 blue; 3 blue, 3 green, 15 red; 12 red, 6 green, 13 blue; 15 red, 6 green, 10 blue\n" +
            "Game 87: 4 red, 4 blue; 6 red, 2 blue; 5 blue, 3 green; 4 blue, 2 red\n" +
            "Game 88: 4 blue, 7 green; 2 blue, 7 green; 6 green, 4 blue; 1 red, 1 blue, 2 green; 11 green, 3 blue\n" +
            "Game 89: 1 blue, 12 green, 11 red; 3 red, 7 blue, 1 green; 7 green, 8 red; 6 blue, 2 green, 3 red; 7 red, 8 green; 11 blue, 5 red, 12 green\n" +
            "Game 90: 1 green, 12 red, 17 blue; 14 red, 17 blue, 9 green; 6 green, 9 red, 11 blue\n" +
            "Game 91: 3 green, 14 blue; 2 blue, 2 green, 6 red; 1 red, 11 blue, 1 green; 3 green, 4 red, 20 blue; 6 red, 2 green, 3 blue; 10 blue, 12 red\n" +
            "Game 92: 6 blue, 7 red; 2 blue, 4 red, 1 green; 4 red, 1 green, 3 blue; 2 red, 5 blue; 8 red, 6 blue; 1 green, 2 blue, 1 red\n" +
            "Game 93: 4 blue, 1 green, 4 red; 8 red, 4 green, 4 blue; 2 blue, 9 red; 1 blue, 4 red; 4 blue, 2 green, 11 red\n" +
            "Game 94: 5 blue, 1 green, 7 red; 1 green, 11 blue, 1 red; 1 green, 15 blue, 4 red\n" +
            "Game 95: 1 red, 3 blue; 1 red, 1 green, 8 blue; 3 red, 1 green, 3 blue; 3 red, 6 blue; 6 blue\n" +
            "Game 96: 4 green, 1 blue; 7 green, 3 red; 2 blue, 9 red, 16 green; 3 blue, 4 red, 11 green\n" +
            "Game 97: 6 green, 8 blue; 1 blue, 1 green; 3 green, 4 blue; 8 blue, 5 green, 2 red\n" +
            "Game 98: 18 blue, 6 green; 11 green, 3 blue, 7 red; 18 blue, 3 red, 7 green; 5 red, 5 green; 8 blue, 2 green, 11 red\n" +
            "Game 99: 3 red, 2 green, 3 blue; 1 red, 4 green, 1 blue; 2 green, 18 red; 15 red, 1 blue; 2 blue, 9 red, 2 green; 17 red, 3 blue, 4 green\n" +
            "Game 100: 9 blue, 8 red, 16 green; 3 red, 7 green, 8 blue; 1 green, 3 red, 12 blue; 3 green, 14 blue";

    public static String exempleDay2 = "Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green\n" +
            "Game 2: 1 blue, 2 green; 3 green, 4 blue, 1 red; 1 green, 1 blue\n" +
            "Game 3: 8 green, 6 blue, 20 red; 5 blue, 4 red, 13 green; 5 green, 1 red\n" +
            "Game 4: 1 green, 3 red, 6 blue; 3 green, 6 red; 3 green, 15 blue, 14 red\n" +
            "Game 5: 6 red, 1 blue, 3 green; 2 blue, 1 red, 2 green";

    public static String day3Input = "...................15....904...........850.................329...................13....................................871....816....697....\n" +
            "...........53.497........................%....906...610.......*.............735#..&...*......558...68...............68..*......&....*.......\n" +
            "..........*....$....................132.........*..........844....875................350............*...............*..336.364...649........\n" +
            ".......726.......341..................*...186...358..................*244........57.......@.........738......*.....663.................584..\n" +
            ".............952.*......33......660..704............949......................518*....234.967....551........971..&.......................*...\n" +
            ".......738...*....222......................706.......*..825.............474%...........*...........*.405.........779..............542...405.\n" +
            ".74.........366....................192..........542.737....*760...................623/..730.....718.../.....................$17......%......\n" +
            "...*126.....................%........*.504...=..*.........................................................974...............................\n" +
            "........331/..901.........337..........*...461.698...............*461.....814............................*............975...............165.\n" +
            "..../.........*.....................262.......................313........*........530.56.....567.......897.....*.........*.9................\n" +
            "....953....355...@703..................................609..............462.......%........./...............108.557...501.../...724.........\n" +
            "..............................................=.........%.......46......................533....670...............................*..%630....\n" +
            ".........................91...382*204.........154..%.............+.524.995..............=.....*...........7..........692.92*56...73.........\n" +
            ".685....*....70.189.......*.........................773...830/....../....*........=.........565.............464................$....738..130\n" +
            ".........938..*........993..............*.................................243...340...753...........*...882...............108.647....*......\n" +
            "..............762..........348.......280...............364*526...........................*........552.....=....25..682....*.........164.....\n" +
            ".....948..............813../....644......62........................................#.....657......................*.........................\n" +
            "......*...........................*.................$745.......739.....*...399...30............&..@...........924.117..........309..........\n" +
            "...883....544.....33.........585=.428.146................288.....*..853....*...........*891.409....429..460...*..........997....*........187\n" +
            ".............*818........829..........*....846..............................248.....574..................*....789.......*.....965....-..*...\n" +
            "......=.....................*..........370.......850+.............313...........................573....621...............268.......58..800..\n" +
            "....67....287.............481..709...............................*.......#74...................*.................965........................\n" +
            "............@.291.............*.........607*....950.475..309...66..932........395..374..........155.891....472..*......774.............&....\n" +
            "....207..........%..262......543..887/......711....*.......+......*............*...*........823............*...93...........377.....764.....\n" +
            ".....*...968.951.......#................................$.........453...366..736.972........*.............697........*618...&...............\n" +
            "....984..*...............-.......................884..23......492.....*..*................70..523.....25........$.....................370...\n" +
            "..................870...187.......548#.522..458.....*..........*....956......535....../.........*.525*........197....@..*266...123.....*....\n" +
            ".........501.....*..........................&.....323........257........956..*........80..946.592.................211.........*.........311.\n" +
            ".....380*.....867...653..347....................*........93=...........*......515..........-...................................678..........\n" +
            "..........876......&....*.......&631.950.647...631...@...........=...705..914................739..............319......713.........*97.#918.\n" +
            ".....805...*..........118................-.........790....559..51........../........*.........*......550......*........./.......647.........\n" +
            "......-..428.....599......813................413..................280............840.654.......91.....*...........236.......$...............\n" +
            ".............=...%.......*.....77...................#.492............................................96..........@.......175....%...........\n" +
            "......*427..569..........47......................999......314.....636*253.................764.................27......-..........415..386...\n" +
            "...142................$................@..320........969...................882*311...............#..751...........=....649...........*......\n" +
            ".........*723..993.976....638........475................=..800.......................*764.710...574....*964....831..........473......531....\n" +
            "...%..486...................*....#..................................831...........375........*........................=824......21..........\n" +
            "559.........................441...316................................./....................618.407.......83.......972...............91......\n" +
            "......*.....25..741...................%...............*63.546$..905......27........861.756........*.......*..........*...28...57............\n" +
            ".......794....*./........782...236....47...........937...........*..755....*505..............23.948.......560.532...421....*..#.........405.\n" +
            "............566.................*........-850..872.......90....229...+..........978..684............225..................675.....591...*....\n" +
            ".............................296..243...........+....691...................311.........$......321......@......827....$13.......$....&..530..\n" +
            ".....664..422$....613.....@.........%.401/.$974.....-.........%.145....729......*........./.......106............%.......=.....611..........\n" +
            ".......$.........*.......857...147*.............591........+.46..*.....=........306.67*...818.............................261....../........\n" +
            "............823...785..............340.........-....564..777......456.......%....................891.................560...........642..181.\n" +
            ".....394.....*................226..........423..............................539.................*............640&.............535...........\n" +
            ".......@.....626..317..329....*...92........+..................374....827............*.683+....771....529.........303..........*............\n" +
            ".........172.....-........*......*.....332...........288..229..+.........*.786=....468.............*....*...........*....461...249..=.......\n" +
            "....974...*............901..@....130..*..............$...*..........4.573................163......429....808.464*47..231....@......964......\n" +
            "........183.................582........11...............310.....774.*.....567.............*....36...........................................\n" +
            ".......................939.....................*826............@.....892..........481......266.*...-253.........106.830....235......*..841..\n" +
            "727.........177#.........&.......507........301..........................550..242*.....+./.....686.......@.446.*.....*.......*....894..*....\n" +
            "....67...............468.....&......&..596......................817.600...............85.5.............973...$.805...513......378.......388.\n" +
            "...........*247.........*.....974.........*263....329....476....*............721............723.....................................358.....\n" +
            "........784.....434.....667.......................*............615.195.612...............................540#........347...........*........\n" +
            "...............*.................76......121...659........@555..........-.............201......................866............628.505.509...\n" +
            ".............515........../.................#....................281..%...656............*670.419.......799.......*...510.786...*.......&...\n" +
            "....993.................540.373....709.............705............*...132..#........298$......*...232....*..@..878.......*....528...#.......\n" +
            "....$.........615.............*..........948..........*........565................%..........465..#.....497.67....................631.......\n" +
            ".........138....#....417......123...........*.......546...821...................114..=............................258.859=.380-.............\n" +
            ".....734*.............../.............833..399..........................+............780...288..............117..@...................925....\n" +
            "................*860..........228........*...............................956....390*........=..........%...*..........839...373......*......\n" +
            "..802........369........641.............763.....154.24...............302............620..............150.403.......*.........*....647.......\n" +
            "...................................&........466*.....@..................*827....530.............................129.628.....923.........=866\n" +
            "..........&......&.............824.573.................669.........................$.....374..627...........698.....................759.....\n" +
            ".......499....%.812.857*653...................668..........879.......974................../......*926...852.........................-....832\n" +
            "...646......284..............708...369...........*808................-.......705.......@...............%.............492.462............*...\n" +
            "....................959......#.......*....872..........................102....*.........80..839....996..............*.....%........83...49..\n" +
            ".785............363..*.............49.......*.......667.....797....224.......586..............&....*...34..673.......650....................\n" +
            "....*..*132....*.....225...................631..350..*.........*....*.............941....=.......52....*.................406...546..........\n" +
            ".543............760.........305..325...330.......+.................621...........*.......63..#.......268..239...................#...........\n" +
            "........658..................*............*...........735......820.....145....419...........91..489.........*......404.......*....#.........\n" +
            "..........=....415+.....38$....844...+..366.............*.......*......*..............................43....945.....#.....563.205..211..183.\n" +
            "......267.......................*...519.....730........836..........277...........808...........504...&................................#....\n" +
            ".....*..................705/....575..........*....../..........$866.........=.......*...975......#.......183.931........%.......611.........\n" +
            ".......135.......284........................246.653.972..............365..191.....376...*.....&.........*......*.........994...@.....11.....\n" +
            "...440../.........*.............................*..............415.....................985..838......677.......109...................*......\n" +
            "...@............224....399.727$......68#..........................$......432.....214$.....................#.................591....686......\n" +
            "..........&.......................................658........143....779.+....942......$.............885....567..........$...................\n" +
            ".461.......33....277.407......108..............47.*.............*...........*.......$.811............................390....................\n" +
            "..........................907*.....#397..307...*....197.12.....3...738....254.85..393...............713..700..741...........176.....883.....\n" +
            "..316........180...........................*.758...................-...........................................*............*...............\n" +
            "....*..../........871...338..165.........683............455...701*......................540....255.......$....858........277....28....+.....\n" +
            "...660.469..912...#..........%......743.........439.....-.........206......363..........*.......*.......640............................144..\n" +
            "..............*.........443...............610.............803.............*.............879...658............$................189...........\n" +
            "...........172......794........98..............646......................662..............................*....49.-210.523.257....*..........\n" +
            "...87..662.....#.......*667....%..408..........*............220...524............=.....742..39..160....64.636..........*..*....974..378.....\n" +
            "...*.....*.....42..&.............=....371*.....804.................*..#....../.240.....*........................395%..461..818.....*........\n" +
            "....706.398........452....500.............406..........57*380....365.42...635.......131...........18.....538.....................403........\n" +
            "..............143........*.........80............740..........................*245......784........-...........708...................&.297..\n" +
            ".230...........*.......373..341...........................$438.......*.................=.............874&..959*...........192......829.#....\n" +
            "...#..........476..647.....*......................................431.728..........................................50.....$.................\n" +
            "........334...........*731.930......=........966........*323...................301.....%....404...............879....*372.....208.134.......\n" +
            "...........*.....................163..........*......509......................%.....&..785.......................*...............*..........\n" +
            "...768..329....199........................................797......*368..........873..........26.565....651.....664......111..........217...\n" +
            "................*.....26.......705*76....415.............*................................749..........*..................#......545-..%....\n" +
            "....-....473..517......*...............5*....449..........68........................751.......*399......401.................................\n" +
            ".730......#.........240...&..65.718.87......*.....532..............-....567............*....................675.......67..463...............\n" +
            ".....289#....509........200......*...*....852....................885...+....663..72..507......998.&954..213....$.....*.........672..........\n" +
            "..............................403.....129........377-....................../....&.................................473...........*...........\n" +
            ".........855=.........250...................961........860*916.......981..........326.........633..404................676.%566..120.........\n" +
            "892...........532.............754.......866*....790..................#........819*..............*.........%.44..=......*............29......\n" +
            "....@527.......*..................600............../...$568.....800.....................179..528........613.....358...949...................\n" +
            "................302...807............*..895.................+.....@.....-...........................980...........................736.......\n" +
            "........217...=......*............879.....+.-..........%.....793.......442.......422............209*.......&.......969....240.378...*.......\n" +
            "....340*.....145...%.596....................23....703...217................372..........610.................129.......*........../.....=....\n" +
            ".................790.....&............904............=............795......*.......385=...+.....88*143...............891....406.......79....\n" +
            "............*749.........31..............*....318.................+.......317.................................%419.............*392.........\n" +
            "....854..797......*..500...............614.1...*..............803.....451............330.159.143.598.......+......./827...............717...\n" +
            "...@............924.*........................245............-.&..........*...606................*...........461............604....#....*....\n" +
            "....................73....160..406.150...............933.957...................%.......419.........665..*.........-.......*.....721..573....\n" +
            "....*915.........40................*...%.............*........584.......929......377....*..404.935....&..870.....93........395..............\n" +
            ".781.............@...........632.......710....769.323............$.........*.........904.....*...*.....................859..................\n" +
            ".....=.......................*...646............-.........................52................149...414....................*........%.........\n" +
            "...51....524.625..........328...*.................................295.734......@..........................856.291.695....367..218..787..8...\n" +
            ".........../.*................339........................576/.417*...........445...@........................%....................-..........\n" +
            "....869.85...316.....308...............345.......749.............................264.............775..777...............................89..\n" +
            ".......*...............#.........$....*..........*....../.....786.713*52.................357.......&./.........#......971....74.305....-....\n" +
            "............................325..770..167..@.....265..+..883................................+...57..........312.......*........*............\n" +
            "......+.....266.....788.111....*..........342........588.......939..393*717.............488....*....................401....249...255........\n" +
            ".......308..*............#.....816....465..........*.....492..@.............581.........-.......397..709*.................$.....*...........\n" +
            ".............511.....881...+.........+..........178..524*..............150..../..720.......843...........964....129.../......908............\n" +
            ".......749.............*.526.$............800............................*.........*...500....*.../.................487..........200........\n" +
            "..668......*639......932......139.726................#...51..436$..................775...*...834..874.......%..............859+......439....\n" +
            "........810........................*.......805.......100..*...........999.....743......169............477...961......973............$.......\n" +
            ".574...........6*262........398....204......*.....%.......525...........*.........................412..*.........376...*.@43....=......=....\n" +
            "....*836....................................25...619............658.....172.......................*...408...........*........%...776..802...\n" +
            ".............307.......&........537..988..............128..-.....*..........................118...327......296.......967..991...............\n" +
            ".....899...$...*....788.....829......=....................559.722.......519.........385$...+..................*.323*..............*123......\n" +
            "........*.930...674...........*..........447.......801..............957....................................111......767..34....556..........\n" +
            "..565.644..............18.....472.........*...8........................*........258........901.................296.......*..........*.......\n" +
            "....*............995=....*................649.*...151.........437%...445.747......-.........&......#......%.....*.........800....357.240....\n" +
            "....476.491/.931.......121..732*940..682......975..$.....*..................+.358.............../.363....152.264........$...................\n" +
            ".............=....730*..................*584...........234.........996.................*.....701........................499............649..\n" +
            "......................672......@.............................958.....&.+...........983.673........233.@981........760.......................\n" +
            "..942.993@......293...........939..&....@.........867..92.....*........679.........................*.............*.......27...998...........\n" +
            "....#.......230.$...................36.24....809..#....*...660.....$.......748..199.-.............717...@......................../..........\n" +
            "......*95..............647...$..............-.........461..........757...........*...68...............728..210*680..708......$.....246......\n" +
            "...355.........*..........*.538...%..............................-...............977....209*.......................*.........141.....*......\n" +
            "...............680.....670.........784........171..799.........317..........................844........166........289.................463...";

    public static String exempleDay3 = "467..114..\n" +
            "...*......\n" +
            "..35..633.\n" +
            "......#...\n" +
            "617*......\n" +
            ".....+.58.\n" +
            "..592.....\n" +
            "......755.\n" +
            "...$.*....\n" +
            ".664.598..";

    public static String testCaseDay3 = ".2.\n" +
            ".*.\n" +
            "585";
}
